# Generated by Django 4.0.4 on 2022-04-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidateaura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('party', models.CharField(max_length=30)),
                ('constituency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='candidatebiht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('party', models.CharField(max_length=30)),
                ('constituency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='candidatechh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('party', models.CharField(max_length=30)),
                ('constituency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='candidatepali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('party', models.CharField(max_length=30)),
                ('constituency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='candidatepatn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('party', models.CharField(max_length=30)),
                ('constituency', models.CharField(max_length=50)),
            ],
        ),
    ]
