# Generated by Django 4.0.4 on 2022-04-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='candidatechh',
            new_name='Candidatechha',
        ),
    ]
