# Generated by Django 4.0.4 on 2022-04-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_candidatechh_candidatechha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='candidatebiht',
            new_name='Candidatepalg',
        ),
        migrations.DeleteModel(
            name='Candidatechha',
        ),
        migrations.DeleteModel(
            name='candidatepali',
        ),
        migrations.DeleteModel(
            name='candidatepatn',
        ),
    ]
