# Generated by Django 4.0.4 on 2022-04-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_candidatebiht_candidatepalg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votergovt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pannumber', models.CharField(max_length=10)),
                ('constituency', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Voterregisteredamroha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('pannumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Voterregisteredpalghar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('pannumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
