# Generated by Django 4.0.4 on 2022-04-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_uidamroha_uidpalghar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
